### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by tkf** [c42f/TerminalLoggers.jl#11]
There is a setup in `.travis.yml` but it is not deployed properly because `DOCUMENTER_KEY` is not setup.

@c42f Can you set configure it for Travis CI (or GitHub Actions)?

https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

**Comment by c42f** [comment]
For sure, will do. I'll read up on Travis vs github actions. Do you have any preference between those for documentation at this stage?

**Comment by tkf** [comment]
I think GitHub Actions is a bit better because:

* it supports `push_preview` https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs
* we keep colorful test log in Travis

But I don't mind using Travis at all, especially since you already half setup Travis.

**Comment by c42f** [comment]
Good call, GitHub Actions seems very slick, should be working now I hope (#14).
I've turned `push_preview` on which is pretty cool.
