### ISSUE TITLE
ETA for progress bars

### ISSUE THREAD

**Issue by tkf** [c42f/TerminalLoggers.jl#3]
It would be nice to print ETA like ProgressMeter.jl does.  To do this, I think we need to record `progress` value and `time()` when the logger received

```julia
struct ProgressBar
    init_progress::Float64
    init_time::Float64
end

struct TerminalLogger <: AbstractLogger
    ...
    bars::Dict{Symbol, ProgressBar}
end
```

Current `TerminalLogger` is nice as it is mostly "stateless" (except `sticky_messages`) and `bars` would break this property.  But I think it would be required anyway at some point to support something like nested progress bars https://github.com/JunoLab/ProgressLogging.jl/issues/7#issuecomment-544033475 / https://github.com/JunoLab/ProgressLogging.jl/issues/8.

**Comment by c42f** [comment]
Yes, an ETA would be cool.

I'm fine with `TerminalLogger` being more stateful, I don't think we can make a good UI without tracking a fair bit of state.

For access to `sticky_messages`, we perhaps should move that out of `TerminalLogger` anyway and make it global in some way. It's a model of the connected terminal and there's generally only one of those (I guess there could be more but that seems like a funky thing we could deal with later).

Yikes, dynamic `gensym()` observed in ProgressLogging #7 is not ideal, let's fix that :-)
