### ISSUE TITLE
refine output in fast math mode?

### ISSUE THREAD

**Issue by daviehh** [c42f/TerminalLoggers.jl#31]
When julia is launched with the `--math-mode=fast`, running the minimum example
```
n = 10
@withprogress for i = 1:n
    sleep(.1)
    println("$i...")
    @logprogress i / n
end
```
would printout some error messages
```
┌ Error: Exception while generating log record in module Main at /Users/david/.julia/packages/ProgressLogging/g8xnW/src/ProgressLogging.jl:385
│   exception =
│    InexactError: trunc(Int64, NaN)
│    Stacktrace:
│     [1] trunc at ./float.jl:703 [inlined]
│     [2] round at ./float.jl:367 [inlined]
│     [3] printprogress(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::TerminalLoggers.ProgressMeter.BarGlyphs, ::Float64, ::String, ::Float64, ::Float64) at /Users/david/.julia/packages/TerminalLoggers/YeJjc/src/ProgressMeter/ProgressMeter.jl:65
│     [4] printprogress(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::TerminalLoggers.ProgressBar) at /Users/david/.julia/packages/TerminalLoggers/YeJjc/src/ProgressBar.jl:41
...
```

Reason is, when julia is launched with the `--math-mode=fast`, julia would assume no NaN is present in the calculation and `isnan(NaN)` would return false. Therefore, 
https://github.com/c42f/TerminalLoggers.jl/blob/b87cf482893b0d8c9fb07f1bd8df42c1f654f43f/src/ProgressMeter/ProgressMeter.jl#L46
won't set `percentage_complete` to 0 in fast math mode, and

https://github.com/c42f/TerminalLoggers.jl/blob/b87cf482893b0d8c9fb07f1bd8df42c1f654f43f/src/ProgressMeter/ProgressMeter.jl#L65

would give the error message for the newly-created progress-bar with `@withprogress`, which is initialized with `NaN` as an indeterminate state: [corresponding code in ProgressLogging.jl](https://github.com/JunoLab/ProgressLogging.jl/blob/5a900a56b559abdee59526008320070198bec89a/src/ProgressLogging.jl#L326)

One can ignore the error message, or is it better to wrap the round-to-int with a try-catch block using a new variable
```
round_perc_ = try
        round(Int, percentage_complete)
    catch
        0
    end
```
and use `round_perc_` in
https://github.com/c42f/TerminalLoggers.jl/blob/b87cf482893b0d8c9fb07f1bd8df42c1f654f43f/src/ProgressMeter/ProgressMeter.jl#L54
and
https://github.com/c42f/TerminalLoggers.jl/blob/b87cf482893b0d8c9fb07f1bd8df42c1f654f43f/src/ProgressMeter/ProgressMeter.jl#L65

Thanks! included a PR, maybe the name `round_perc_` could be something else?

**Comment by tkf** [comment]
I think we should use `@logprogress nothing` in ProgressLogging.jl.  The progress (fraction) value can actually be `Union{Float64,Nothing}`.

**Comment by daviehh** [comment]
@tkf  Thanks for the suggestion! submitted two PRs in `ProgressLogging.jl` and here to change the nan logic to check for `nothing`.
